# Initialize the canvas package with the following definitions

from .create_food_table_canvas import CreateFoodTableCanvas
from .stored_food_tables_canvas import StoredFoodTablesCanvas
from .consumed_food_items_canvas import ConsumedFoodItemsCanvas